### ISSUE TITLE
How to enable "cuda" for using in PyTorch?

### ISSUE THREAD

**Issue by sakarayajitesh** [petronetto/docker-python-deep-learning#12]
When I run `torch.cuda.current_device()` it's giving `AssertionError: Torch not compiled with CUDA enabled`

**Comment by petronetto** [comment]
You need to rebuild the container and compile PyTorch with CUDA, but the main goal of this container is to be small, is more focused on study rather than production.

In case you need to use CUDA, I suggest use the official docker images, they are way larger but is ready for production: https://hub.docker.com/r/pytorch/pytorch/tags
